### ISSUE TITLE
支持对图片 pipeline 处理吗

### ISSUE THREAD

**Issue by kawa23** [miaoerduo/easy-pipeline#1]
@miaoerduo 你好，非常感谢你分享的这个基于python pipeline 框架，请问该框架可以针对图片进行 pipeline 处理，比如 resize、crop、transpose 等操作吗，可以提供一个相关示例吗，谢谢。

**Comment by miaoerduo** [comment]
main.py里面是Demo，把数字换成图片就可以了。

**Comment by kawa23** [comment]
好的，谢谢。
